### ISSUE TITLE
Identify not working with vector layers

### ISSUE THREAD

**Issue by brentfraser** [geomoose/gm3#522]
v3.6.2-beta
Identify not working for the following demo layers:
* Drawing and Markup (type="vector")
* Cities and Villages (type="geojson") related to #520 
* Expensive Parcels  (type="mapserver-wfs")

There's a bug in map.js. In lines 577,578 selection. needs to be replaced with selection[0]. (or something better).  Here's my diff:

```
diff --git a/src/gm3/components/map.js b/src/gm3/components/map.js
index e3f98cb..5be62da 100644
--- a/src/gm3/components/map.js
+++ b/src/gm3/components/map.js
@@ -574,8 +574,8 @@ class Map extends React.Component {
         const result_features = [];

         const selection = query.selection;
-        if(selection && selection.geometry && selection.geometry.type === 'Point') {
-            const coords = selection.geometry.coordinates;
+        if(selection && selection[0].geometry && selection[0].geometry.type === 'Point') {
+            const coords = selection[0].geometry.coordinates;
             src.forEachFeatureAtCoordinateDirect(coords, (feature) => {
                 result_features.push(format.writeFeatureObject(feature));
             });
```

**Comment by theduckylittle** [comment]
Fixed in #533

**Comment by brentfraser** [comment]
Now works on geojson and mapserver-wfs,  but still a problem with Drawing and Markup layer.

- Turn off all layers except Drawing and Markup
- Draw a polygon
- Do Identify in the polygon

Results are not returned

**Comment by theduckylittle** [comment]
Try editing the properties and assigning a label.
